language: python
python:
  - "3.4"
  - "3.5"
  - "nightly"
install:
  - "pip install -r requirements.txt"
  - pip install coverage
  - pip install coveralls
script:
  - nosetests -v --with-coverage --cover-erase
after_success:
  - coveralls
